name: Build Unsigned IPA

on:
  workflow_dispatch: # This allows you to trigger the action manually

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Xcode Command Line Tools
      run: xcode-select --install

    - name: Install Dependencies
      run: |
        brew install openssl xquartz node

    - name: Download xcFrameworks
      run: |
        ./downloadFrameworks.sh

    - name: Build Python and associated libraries
      run: |
        cd cpython
        sh ./downloadAndCompile.sh

    - name: Generate exportOptions.plist
      run: |
        cat << EOF > exportOptions.plist
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>compileBitcode</key>
            <false/>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>signingStyle</key>
            <string>manual</string>
            <key>signingCertificate</key>
            <string></string>
            <key>provisioningProfiles</key>
            <dict/>
        </dict>
        </plist>
        EOF

    - name: Build the Xcode Project without signing
      run: |
        xcodebuild -project a-Shell.xcodeproj \
                   -scheme a-Shell \
                   -configuration Release \
                   -sdk iphoneos \
                   -arch arm64 \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGNING_ALLOWED=NO \
                   build

    - name: Package the build into an IPA
      run: |
        xcodebuild -exportArchive \
                   -archivePath ${{ github.workspace }}/build/a-Shell.xcarchive \
                   -exportOptionsPlist ${{ github.workspace }}/exportOptions.plist \
                   -exportPath ${{ github.workspace }}/build/a-Shell.ipa \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO

    - name: Archive IPA
      uses: actions/upload-artifact@v2
      with:
        name: Unsigned-IPA
        path: ${{ github.workspace }}/build/a-Shell.ipa
